id: PB436C8C0
initial_creation_type: input
source_metadata:
  Title: Āryamañjuśrīmūlakalpam
  Editor: Shastri, M. M. T. Ganapati
  Publisher: Sri Satguru Publications
  Place of Publication: Delhi
  Year: '1925'
  Atha prathamaḥ parivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha dvitīyaḥ parivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha tṛtīyaḥ parivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturthaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Pañcamaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ṣaṣṭhaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Saptamaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Aṣṭamaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha navamaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha daśamaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Athaikādaśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha dvādaśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha trayodaśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha caturdaśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha pañcadaśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha ṣoḍaśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha saptadaśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Athāṣṭādaśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha ekonaviṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha viṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha ekaviṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha dvāviṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha trayoviṃśatitamaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha caturviṃśatitamaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha pañcaviṃśatitamaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha ṣaḍviṃśatitamaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Saptaviṃśatitamaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha aṣṭāviṃśatitamaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Athaikonatriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha triṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Athaikatriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha dvātriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha trayastriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha catustriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha pañcatriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha ṣaṭtriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha saptatriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Athāṣṭātriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Athaikonacatvāriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha catvāriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha ekacatvāriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha dvicatvāriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha tricatvāriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha catuścatvāriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha pañcacatvāriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha ṣaṭcatvāriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha saptacatvāriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Athāṣṭacatvāriṃśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Athaikonapañcāśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha pañcāśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha ekapañcāśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha dvipañcāśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha tripañcāśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha catuḥpañcāśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha pañcapañcāśaḥ paṭalavisaraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:13:34.921728'
last_modified_at: '2022-03-08T16:13:34.921740'
